### ISSUE TITLE
Issue - IE 11

### ISSUE THREAD

**Issue by brandonmytty** [EMCECS/ecs-browser#10] opened 2018-11-09 15:34 UTC
Unable to list contents of bucket in IE 11.

**Comment by DavidASeibert** [comment] 2018-11-13 20:37
@brandonmytty can they try IE12? The problem is apparently a Javascript issue with IE11 that's supposedly fixed in 12. Oops, just checked and 12 was never released...

**Comment by DavidASeibert** [comment] 2018-11-16 20:30
Fixed in v1.0.0rc3.

**Closed as completed by DavidASeibert** 2018-11-16 20:30 UTC
